# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareerLadder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for MoreMe
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTVibration'
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  pod 'FirebaseMessaging'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  
  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  
  pod 'RNShare', :path => '../node_modules/react-native-share'
  
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  end